// scripts/build-instructions.ts
//
// Reads src/mcp/instructions/instructions.md and writes
// src/mcp/instructions/instructions.generated.ts with the content embedded
// as a JSON-stringified string literal. Safe against any code-fence /
// backtick / ${} content in the markdown.

import { execSync } from "node:child_process";
import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = path.resolve(
	path.dirname(fileURLToPath(import.meta.url)),
	"..",
);
const srcFile = path.join(repoRoot, "src/mcp/instructions/instructions.md");
const outFile = path.join(
	repoRoot,
	"src/mcp/instructions/instructions.generated.ts",
);

async function main() {
	let markdown: string;
	try {
		markdown = await fs.readFile(srcFile, "utf-8");
	} catch (err) {
		if ((err as NodeJS.ErrnoException).code === "ENOENT") {
			console.error(
				`instructions.md not found at ${srcFile}; cannot generate instructions.generated.ts`,
			);
			process.exit(1);
		}
		throw err;
	}
	const out = `// AUTO-GENERATED by scripts/build-instructions.ts. Do not edit by hand.
// Re-run \`pnpm run build:instructions\` to regenerate.

export const INSTRUCTIONS = ${JSON.stringify(markdown)};
`;
	await fs.writeFile(outFile, out);
	// Auto-format with Biome so the committed file always passes `pnpm lint`.
	execSync(`pnpm exec biome format --write ${outFile}`, { stdio: "inherit" });
	console.log(`Wrote instructions (${markdown.length} chars) to ${outFile}`);
}

void main();
